apiVersion: v1
kind: Service
metadata:
  name: frontend
spec:
  type: NodePort
  selector:
    app: tero
    tier: frontend
    track: stable
  ports:
    - protocol: TCP
      port: 80
      targetPort: frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tero
  template:
    metadata:
      labels:
        app: tero
        tier: frontend
        track: stable
    spec:
      containers:
        - image: terosaarikivi/frontend:1.0.1
          name: frontend
          ports:
            - name: frontend
              containerPort: 3000
